# Description:
#   - A github workflow for building and uploading the DEMO app (apk and ipa)
#   - This workflow calls the reusable build-app.yml workflow
# REF:
#   1. https://docs.github.com/en/actions/using-workflows/reusing-workflows

name: Build DEMO Apps

on:
  workflow_dispatch:
    inputs:
      app-name:
        required: true
        default: 'demo-app'
        description: 'App Name'
      build-branch:
        type: choice
        required: true
        default: 'develop'
        description: 'Build Branch'
        options:
          - develop
          - master
          - support/cts
      android:
        type: boolean
        default: false
        required: false
        description: 'Build Android'
      ios:
        type: boolean
        default: false
        required: false
        description: 'Build iOS'
      publish-to-gh:
        type: boolean
        default: false
        required: false
        description: 'Publish to GitHub'
      gh-version:
        required: true
        default: 'v1.1.0'
        description: 'Github Version'

# Fix Resource not accessible by integration 403 error
permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Build DEMO App
    uses: ./.github/workflows/build-app.yml
    with:
      repo-url-var: DEMO_REPO_URL
      prepare-code-var: APP_PREPARE_CODE
      app-name: ${{ github.event.inputs.app-name }}
      ios: ${{ github.event.inputs.ios == 'true' }}
      android: ${{ github.event.inputs.android == 'true' }}
      build-branch: ${{ github.event.inputs.build-branch }}
      gh-version: ${{ github.event.inputs.gh-version }}
      publish-to-gh: ${{ github.event.inputs.publish-to-gh == 'true' }}
    secrets:
      CODE_PASS: ${{ secrets.CODE_PASS }}
      OSS_AK: ${{ secrets.OSS_AK }}
      OSS_SK: ${{ secrets.OSS_SK }}
      ERDA_GIT_TOKEN: ${{ secrets.ERDA_GIT_TOKEN }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      IOS_DISTRIBUTION_CERTIFICATE_PASSWORD: ${{ secrets.IOS_DISTRIBUTION_CERTIFICATE_PASSWORD }}
      IOS_DISTRIBUTION_CERTIFICATE_BASE64: ${{ secrets.IOS_DISTRIBUTION_CERTIFICATE_BASE64 }}
      IOS_AD_HOC_PROVISIONING_PROFILE_BASE64: ${{ secrets.IOS_AD_HOC_PROVISIONING_PROFILE_BASE64 }}
